project_id = "bpfozomwvofmxifikqfn"

[functions.generate-quiz]
verify_jwt = false

[functions.generate-scores]
verify_jwt = false

[functions.generate-description]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false
